language: java

jdk:
  - oraclejdk8

branches:
  except:
    - site

cache:
  directories:
    - $HOME/.m2
    - .cache

# override default command since it doesn't skip checkstyle
install:
  - tools/install-repackaged

script:
  - mvn -D environment=test verify

after_success:
  - bash <(curl -s https://codecov.io/bash)
